
dist: trusty

language: php
php:
  # until 2019-12-01
  - '7.1'
  # until 2020-11-30
  - '7.2'
  # until 2021-12-06
  - '7.3'

before_script:
  # Install packages
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install -n ;

script:
  # Test all the things
  - vendor/bin/phing

after_script:
  # Track code coverage
  - if [[ -n "$CODACY_PROJECT_TOKEN" ]]; then
        vendor/bin/codacycoverage clover build/coverage/xml ;
    fi
